config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'groups#index'
  resources :users,  only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users,   through:  :members
  has_many :messages

  validates :name,   presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end

end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  mount_uploader :image, ImageUploader

  validates :content_or_image, presence: true

  def content_or_image
    content.presence or image.presence
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :members
  has_many :groups,  through:  :members
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  # GET /groups/new
  def new
    @group = Group.new
    @group.users << current_user
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end

  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
     if @group.update(group_params)
      redirect_to root_path, notice: 'グループを編集しました.'
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, { :user_ids => [] })
    end
  end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    @new_messages = @messages.where("id > ?", params[:id])
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group)}
        format.json
      end
    else
      redirect_to group_messages_path(@group)
    end
  end

  def destroy
    @group.messages.destroy_all
    redirect_to group_messages_path(@group)
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id, group_id: params[:group_id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where("name LIKE(?) AND id != ?", "%#{params[:keyword]}%", current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_chat.haml
.chat
  .chat-header
    .left-header
      .left-header__title チャットグループ１
      .left-header__members Member： 誰々
    .right-header
      Edit
  .messages

    .message
      .upper-message
        .upper-message__user-name
          ユーザー名
        .upper-message__date
          ポストされた日付
      .lower-message
        .lower-message__text
          メッセージ

    .message
      .upper-message
        .upper-message__user-name
          ユーザー名
        .upper-message__date
          ポストされた日付
      .lower-message
        .lower-message__text
          メッセージ

    .message
      .upper-message
        .upper-message__user-name
          ユーザー名
        .upper-message__date
          ポストされた日付
      .lower-message
        .lower-message__text
          メッセージ

  .footer
    %form.form{action: "./", method: "get"}
      %input.form__text{type: "text", placeholder: "type a message"}
        .image-button
          %label
            %i.fa.fa-picture-o.fa-lg
            %input.image-button__image{type: "file", name: "img", style: "display: none"}
      %input.form__submit{type: "submit", value: "Send"}

app/views/groups/_form.html.haml
= form_for (@group) do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, placeholder: "グループ名を入力してください。", class: "chat-group-form__input"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "user-search-field"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input.chat-group-form__input#user-search-field{placeholder: '追加したいユーザー名を入力してください', type: 'text'}
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label "チャットメンバー", class: "chat-group-form__label", for: "chat-group-users"
    .chat-group-form__field--right
      #chat-group-users
        - @group.users.each do |user|
          .chat-group-user.clearfix
            %input{name: 'group[user_ids][]', type: 'hidden', value: "#{user.id}"}
            %p.chat-group-user__name
              = user.name
            %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "Save", class: "chat-group-form__action-btn"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: {group: @group}

app/views/groups/index.html.haml
.wrapper

  = render "shared/side_bar"
  .chat

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: {group: @group}

app/views/groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @group.name

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_message.html.haml
.message{"data-message-id": message.id}
  .upper-message
    .upper-message__user-name
      = message.user.name
    .upper-message__date
      = message.created_at
  .lower-message
    .lower-message__text
      = message.content
      = image_tag message.image if message.image.present?

app/views/messages/index.html.haml
.wrapper
  = render "shared/side_bar"
  .chat
    .chat-header
      .left-header
        .left-header__title
          = @group.name
        %ul.left-header__members
          = "Members :"
          - @group.users.each do |user|
            %li.left-header__members_member
              = "#{user.name} "
      %div=link_to 'Delete', group_message_path(@group.id, @messages), method: :delete, confirm: 'Are you sure?', class: "delete-header"
      =link_to edit_group_path(@group.id) do
        .right-header
          Edit
    .messages
      /# 本来はcollectionを使ってインスタンスの要素の分だけテンプレートを引き出す。同じメッセージで、複数形、テンプレートファイルは単数系なので、下記のように記述を省略できる。
      = render @messages

    .footer
      = form_for [@group, @message] do |f|
        = f.text_field :content, class: "form__text", placeholder: "type a message"
        %label.image-button
          = f.file_field :image, class: "image-button__image", style: "display: none"
          %i#message_image.fa.fa-picture-o.fa-lg
        = f.submit "Send", class: "form__submit"

app/views/shared/_side_bar.html.haml
.side-bar
  .side-header
    .side-header__username
      = current_user.name
    %ul.side-header__icons
      %li.list
        = link_to new_group_path do
          %i.fa.fa-edit.side-header__icons_icon
      %li.list
        = link_to edit_user_path(current_user) do
          %i.fa.fa-cog.side-header__icons_icon

  .groups
    - current_user.groups.each do |group|
      = link_to group_messages_path(group.id) do
        .group
          .group__name
            = group.name
          .group__message
            = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/update.html.haml
%h1 Users#update
%p Find me in app/views/users/update.html.haml